### ISSUE TITLE
prrte segfaulting with latest PMIx update

### ISSUE THREAD

**Issue by tonycurtis** [pmix/prrte#94]
Thank you for taking the time to submit an issue!

## Background information

Just installed latest PMIx update from github, prrte now segfaults.

(Wes [wessle] is working with me, BTW, this is all related)

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master @ ffe3dd3a51ebde263d97bed352ca7e2d29e4d1b6

### Is the reference server using its internal version of PMIx, or an external one?

External

##### If external, what version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

git master @ a1d3610c2b0eadf68948eead2ec64fc29d799a9e

##### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: x86_64
* Network type: ibv

-----------------------------

## Details of the problem

Run prrte to get DVM, then

```
$ prun -n 1 pmix-client-program
```

generates this from prrte:

```shell
(gdb) r
Starting program: /opt/prrte/bin/prte 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff1c07700 (LWP 52013)]
[New Thread 0x7ffff0dee700 (LWP 52014)]
[New Thread 0x7fffefbcb700 (LWP 52015)]
[New Thread 0x7fffef3ca700 (LWP 52016)]
DVM ready

Thread 2 "prte" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1c07700 (LWP 52013)]
query_cbfunc (status=<optimized out>, status@entry=0, info=info@entry=0x0, 
    ninfo=<optimized out>, ninfo@entry=0, cbdata=0x7fffe800db70, 
    release_fn=release_fn@entry=0x0, release_cbdata=release_cbdata@entry=0x0)
    at ../../pmix-git/src/server/pmix_server.c:2748
2748	../../pmix-git/src/server/pmix_server.c: No such file or directory.
(gdb) bt
#0  query_cbfunc (status=<optimized out>, status@entry=0, info=info@entry=0x0, 
    ninfo=<optimized out>, ninfo@entry=0, cbdata=0x7fffe800db70, 
    release_fn=release_fn@entry=0x0, release_cbdata=release_cbdata@entry=0x0)
    at ../../pmix-git/src/server/pmix_server.c:2748
#1  0x00007ffff741d3ce in pmix_server_job_ctrl (
    peer=peer@entry=0x7fffe800e9c0, buf=buf@entry=0x7ffff1c06c80, 
    cbfunc=cbfunc@entry=0x7ffff73fd1a0 <query_cbfunc>, cbdata=<optimized out>)
    at ../../pmix-git/src/server/pmix_server_ops.c:2541
#2  0x00007ffff7402f4a in server_switchyard (peer=peer@entry=0x7fffe800e9c0, 
    tag=101, buf=buf@entry=0x7ffff1c06c80)
    at ../../pmix-git/src/server/pmix_server.c:3196
#3  0x00007ffff7403897 in pmix_server_message_handler (pr=0x7fffe800e9c0, 
    hdr=0x7fffe800da08, buf=0x7ffff1c06c80, cbdata=<optimized out>)
    at ../../pmix-git/src/server/pmix_server.c:3246
#4  0x00007ffff746b1be in pmix_ptl_base_process_msg (fd=<optimized out>, 
    flags=<optimized out>, cbdata=0x7fffe800d930)
    at ../../../../pmix-git/src/mca/ptl/base/ptl_base_sendrecv.c:719
#5  0x00007ffff6f74345 in event_process_active_single_queue (
    base=base@entry=0x6ca840, activeq=0x6cac90, 
    max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0)
    at event.c:1646
#6  0x00007ffff6f74d47 in event_process_active (base=0x6ca840) at event.c:1738
#7  event_base_loop (base=0x6ca840, flags=flags@entry=1) at event.c:1961
#8  0x00007ffff7427fde in progress_engine (obj=<optimized out>)
    at ../../pmix-git/src/runtime/pmix_progress_threads.c:109
#9  0x00007ffff634c594 in start_thread (arg=<optimized out>)
    at pthread_create.c:463
#10 0x00007ffff60800df in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 

```

**Comment by rhc54** [comment]
Thanks for the report - I believe the referenced commit should have fixed it

**Comment by tonycurtis** [comment]
Yep, looks good.  Thanks
